language: csharp
mono: none

addons:
    apt:
      packages: dotnet-sdk-3.1
    homebrew:
      packages: dotnet

notifications:
  webhooks:
    urls:
      - https://discord-build-notifications.herokuapp.com/travis
      - https://webhooks.gitter.im/e/272ef04cd179f5384ad8
    on_success: change # default: always
    on_failure: always # default: always
    on_start: never # default: never
    on_cancel: always # default: always
    on_error: always # default: always

stages:
    - name: test
    - name: deploy
      if: tag IS present

#--------- TEST JOBS --------------
jobs:
    include:
        - stage: test
          name: test on osx
          os: osx
          # https://travis-ci.community/t/c-build-with-netcore3-1-failed-on-mac-os-and-succed-on-linux/7860
          dotnet: 3.1.200
          install:
            - dotnet restore
          script:
            - dotnet test
        - name: test on linux
          os: linux
          dotnet: 3.1
          install:
            - dotnet restore
          script:
            - dotnet test
        - name: test on windows
          os: windows
          script:
            - choco install dotnetcore-sdk
            - dotnet --version
            - dotnet restore
            - dotnet test
        #-----------------------------------

        #--------- DEPLOYMENT JOB ----------  
        - stage: deploy
          name: nuget & github release
          os: linux
          dotnet: 3.1
          install:
            - dotnet restore
          script: 
            - ./deploy.sh
          env:
              - secure: RYpQwVU5425ML7LNEya4GdPwnIlhgk/xVmMom/yGApRKvgfyZ4V/YJfTsojq+QK+E1nW9pLzwIxyzIYzetw8g4hTBrGhQssErjeQ/fLrY53RXEG8VaIYZKZrQcqEkfpx86JZA9iNewO8pB8N3tE1qHpYNehQV3caQPbijG4XPq5CLgiSy0GtcMKD5xIgN82cyLBVou+U2dJLxKw8xQsyY2Pl0FYY/OL5RGrYS3jgjJ9J1kH508n6Z452nu/XI1M0JKAKH7iqe3fhIOIbZmU0AjoCLKGRDuR0TwvEQYo0VLX6RMcVsmvCl0mGBQ0s+uLs5xf2y7FemgZq/EZ4WH/Ndvc/tVCjcuIGkVwepTJXJaJfI9xS8y77+rj747slsjsVEDLmSRmYx0lzp/sQJIFH16vXIQj4nxePd5MVSC6LWdwE4ZzyIVrBl248gcv5CMPXKXu8FWEhlassbjzPj2cQoYLFQOCiezOtI2xCUR0C6jwxhASEWEh16UDkDycTNSozg85F7a4ETApHPI896ROogHtrrKr3h3O65uY8oxOjmfdrG6HZl0e7vGjECwCXoLlGqpcKs4sR66Vqx3htoII9PDHZsZwblsjphtzkgRuNeeXr2aaZkiPvitXEXnDnsgat/BM4rxF1OHrQ23yH63B9bcV0JrWSmj662dVW1z9Qu48=
        #-----------------------------------
#-----------------------------------

# cache:
#   directories:
#     - $HOME/.nuget/packages  